name: on-merge-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Heroku login container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run:  heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          NEXT_PUBLIC_SUPBASE_URL: ${{ secrets.NEXT_PUBLIC_SUPBASE_URL }}
        run: heroku container:push -a pi-insurance web
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a pi-insurance web