name: on-merge-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "barakmaron/pi-insurance"
          source_branch: "main"
          destination_repo: "barakmaron/pi-insurance-deploy"
          destination_branch: "main"
