name: on-merge-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with: 
          owner: barakmaron
          repository: pi-insurance-deploy
          access-token: ${{ secrets.ACCESS_TOKEN }}