name: on-merge-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: barakmaron
          repository: pi-insurance-deploy
